import Head from 'next/head'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <h2 className="text-2xl mt-10">Upgrade your web development today</h2>
        <h3>Learn web development using the latest tech</h3>
      </main>


    </div>
  )
}
